# Generated by Django 3.0.8 on 2020-09-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('link', models.TextField()),
                ('rating', models.FloatField()),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
            ],
        ),
    ]
