# Generated by Django 3.0.8 on 2020-09-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='head',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
